### PR TITLE
week1 part2 

### PR DESCRIPTION
**Pull request by Brian-Wang0926**
王柏淵

http://13.113.187.108:3000/api/attractions?page=1
http://13.113.187.108:3000/api/attractions?page=0&keyword=劍潭
http://13.113.187.108:3000/api/attractions?page=0&keyword=北
http://13.113.187.108:3000/api/attraction/10
http://13.113.187.108:3000/api/mrts

### CODE REVIEW

**Comment by cwpeng** [comment]
Your server is down.

**Comment by Brian-Wang0926** [comment]
已重新連線，謝謝

**Review by cwpeng — CHANGES_REQUESTED** [review]
`nextPage` of http://13.113.187.108:3000/api/attractions?page=0 and http://13.113.187.108:3000/api/attractions?page=0&keyword=%E5%8C%97 should be 1.

Fix this issue and re-request review.

**Comment by Brian-Wang0926** [comment]
fix next page

**Comment by cwpeng** [comment]
Re-request review from top right corner in this page so that I can review for you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
